const { app, BrowserWindow } = require('electron');
const path = require('path');
const { spawn } = require('child_process');
const http = require('http');

let mainWindow;
let nextServer;

const BASE_URL = 'http://localhost:3000';

const startNextServer = () => {
    return new Promise((resolve, reject) => {
        // Path to the standalone server generated by Next.js
        const serverPath = path.join(process.resourcesPath, '.next/standalone/server.js');

        // In dev mode, we might want to just run next dev, but for packaging we spawn the standalone node server
        // For local testing of "packaging" logic without full build, we can adjust, but here we assume production build.

        // Check if we are in production (packaged) or dev
        const isProd = app.isPackaged;

        if (!isProd) {
            resolve(); // In dev, we assume 'npm run dev' is running separately or handled differently
            return;
        }

        console.log('Starting Next.js server from:', serverPath);

        nextServer = spawn(process.execPath, [serverPath], {
            env: { ...process.env, PORT: 3000, HOST: 'localhost' },
            cwd: path.join(process.resourcesPath, '.next/standalone'),
            stdio: 'inherit'
        });

        nextServer.on('error', (err) => {
            console.error('Failed to start Next.js server:', err);
            reject(err);
        });

        // Wait for port to be ready
        const checkServer = () => {
            http.get(BASE_URL, (res) => {
                if (res.statusCode === 200) {
                    resolve();
                } else {
                    setTimeout(checkServer, 200);
                }
            }).on('error', () => {
                setTimeout(checkServer, 200);
            });
        };

        checkServer();
    });
};

const createWindow = () => {
    mainWindow = new BrowserWindow({
        width: 1200,
        height: 800,
        titleBarStyle: 'hiddenInset', // Mac-like title bar
        webPreferences: {
            nodeIntegration: false,
            contextIsolation: true,
        },
        vibrancy: 'under-window', // Mac vibrancy
        visualEffectState: 'active',
    });

    mainWindow.loadURL(BASE_URL);

    mainWindow.on('closed', () => {
        mainWindow = null;
    });
};

app.on('ready', async () => {
    try {
        await startNextServer();
        createWindow();
    } catch (e) {
        console.error('App init error:', e);
    }
});

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('will-quit', () => {
    if (nextServer) {
        nextServer.kill();
    }
});

app.on('activate', () => {
    if (mainWindow === null) {
        createWindow();
    }
});
